# Generated by Django 5.1.4 on 2024-12-21 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=50)),
                ('album_relese_date', models.DateTimeField(auto_now=True)),
                ('ratings', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')])),
                ('musician_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.musician_model')),
            ],
        ),
    ]
